SET(BLIS_INCLUDE_SEARCH_PATHS
    ${BLIS_HOME}
    ${BLIS_HOME}/include
    ${BLIS_HOME}/include/blis
)

SET(BLIS_LIB_SEARCH_PATHS
    ${BLIS_HOME}
    ${BLIS_HOME}/lib
)

FIND_PATH(BLIS_INCLUDE_DIR NAMES 
    blis.h PATHS ${BLIS_INCLUDE_SEARCH_PATHS}
)

FIND_LIBRARY(BLIS_LIB NAMES 
    blis PATHS ${BLIS_LIB_SEARCH_PATHS}
)

include_directories(SYSTEM ${BLIS_INCLUDE_DIR})

message("BLIS_INCLUDE_DIR: ${BLIS_INCLUDE_DIR}, BLIS_LIB: ${BLIS_LIB}")