option(ENABLE_OPENMP "Enable OpenMP" ON)
if(ENABLE_OPENMP)
    find_package(OpenMP REQUIRED)
    if(OpenMP_CXX_FOUND)
        set(OPENMP_LIB OpenMP::OpenMP_CXX)
    endif()
else()
    set(OPENMP_LIB)
endif(ENABLE_OPENMP)
